# Generated by Django 4.2.13 on 2024-06-02 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertofriendmapping',
            unique_together={('to_user', 'from_user')},
        ),
    ]
